# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CalculateService.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43\x61lculateService.proto\x12\x10\x63\x61lculateservice\"<\n\x05Input\x12\t\n\x01h\x18\x01 \x01(\x01\x12\x0c\n\x04X0_0\x18\x02 \x01(\x01\x12\x0c\n\x04X0_1\x18\x03 \x01(\x01\x12\x0c\n\x04X0_2\x18\x04 \x01(\x01\"e\n\x06Output\x12\x0b\n\x03X_0\x18\x01 \x01(\x01\x12\x0b\n\x03X_1\x18\x02 \x01(\x01\x12\x0b\n\x03X_2\x18\x03 \x01(\x01\x12\x10\n\x08X_next_0\x18\x04 \x01(\x01\x12\x10\n\x08X_next_1\x18\x05 \x01(\x01\x12\x10\n\x08X_next_2\x18\x06 \x01(\x01\x32T\n\x10\x43\x61lculateService\x12@\n\tCalculate\x12\x17.calculateservice.Input\x1a\x18.calculateservice.Output\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CalculateService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUT']._serialized_start=44
  _globals['_INPUT']._serialized_end=104
  _globals['_OUTPUT']._serialized_start=106
  _globals['_OUTPUT']._serialized_end=207
  _globals['_CALCULATESERVICE']._serialized_start=209
  _globals['_CALCULATESERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
